global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:${PORT}"]

  - job_name: "huddle-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["${API_URL}"]
